version: '3.8'

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./settings.py:/app/settings.py:ro
      - ./i18n:/app/i18n:ro
      - ./utils:/app/utils:ro
      - bot_data:/app/data
      - ./.env:/app/.env:ro
    expose:
      - "8443"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8443')"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bot_net

networks:
  bot_net:
    external: true

volumes:
  bot_data:
    driver: local 
