version: '3.8'

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./config.py:/app/config.py:ro
      - bot_data:/app/data
      - ./certs:/app/certs:ro
    ports:
      - "127.0.0.1:8443:8443"
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8443')"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_data:
    driver: local 
